In [2]:
!pip install deepsig

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.1/48.1 kB 764.5 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 8.4 MB/s eta 0:00:00


In [2]:
import numpy as np
from deepsig import aso

In [3]:
seed = 1234
np.random.seed(seed)

# Simulate scores
N = 5  # Number of random seeds
my_model_scores = np.random.normal(loc=0.9, scale=0.8, size=N)
baseline_scores = np.random.normal(loc=0, scale=1, size=N)

min_eps = aso(my_model_scores, baseline_scores, seed=seed)  # min_eps = 0.225, so A is better
print(min_eps)

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:15<00:00, 63.95it/s]

0.22488112073395775


In [5]:
print(my_model_scores)
print('---------------')
print(baseline_scores)

[ 1.27714813 -0.05278056  2.04616557  0.64987848  0.32352901]
---------------
[ 0.88716294  0.85958841 -0.6365235   0.01569637 -2.24268495]


In [6]:
type(min_eps)

numpy.float64

In [7]:
print(min_eps)

0.22488112073395775


In [8]:
import numpy as np
from deepsig import aso

seed = 1234
np.random.seed(seed)

# Simulate scores for three datasets
M = 3  # Number of datasets
N = 5  # Number of random seeds
my_model_scores_per_dataset = [np.random.normal(loc=0.3, scale=0.8, size=N) for _ in range(M)]
baseline_scores_per_dataset  = [np.random.normal(loc=0, scale=1, size=N) for _ in range(M)]

# epsilon_min values with Bonferroni correction
eps_min = [aso(a, b, confidence_level=0.95, num_comparisons=M, seed=seed) for a, b in zip(my_model_scores_per_dataset, baseline_scores_per_dataset)]
# eps_min = [0.006370113450148568, 0.6534772728574852, 0.0

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:07<00:00, 140.31it/s]


In [9]:
my_model_scores_per_dataset

[array([ 0.67714813, -0.65278056,  1.44616557,  0.04987848, -0.27647099]),
 array([ 1.00973035,  0.98767073, -0.2092188 ,  0.3125571 , -1.49414796]),
 array([ 1.22002858,  1.09355682,  1.0626593 , -1.31700386,  0.03273811])]

In [11]:
baseline_scores_per_dataset

[array([ 0.39938318,  1.0932574 , -0.28865265, -2.51631706, -0.41761947]),
 array([-0.29940733, -0.51279437,  0.50144508,  0.54980115, -1.78442607]),
 array([ 0.33305844, -0.84294841,  0.28605538, -1.21624835,  0.53411959])]

In [12]:
from itertools import product

import numpy as np
from deepsig import aso

seed = 1234
np.random.seed(seed)

# Simulate scores for three datasets
M = 40   # Number of data points
N = 3  # Number of random seeds
my_model_scored_samples_per_run = [np.random.normal(loc=0.3, scale=0.8, size=M) for _ in range(N)]
baseline_scored_samples_per_run = [np.random.normal(loc=0, scale=1, size=M) for _ in range(N)]
pairs = list(product(my_model_scored_samples_per_run, baseline_scored_samples_per_run))

# epsilon_min values with Bonferroni correction
eps_min = [aso(a, b, confidence_level=0.95, num_comparisons=len(pairs), seed=seed) for a, b in pairs]
# eps_min = [0.3831678636198528, 0.07194780234194881, 0.9152792807128325, 0.5273463008857844, 0.14946944524461184, 1.0,
# 0.6099543280369378, 0.22387448804041898, 1.0]

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:08<00:00, 118.40it/s]


In [20]:
import numpy as np
from deepsig import multi_aso

seed = 1234
np.random.seed(seed)

N = 5  # Number of random seeds
M = 3  # Number of different models / algorithms

# Simulate different model scores by sampling from normal distributions with increasing means
# Here, we will sample from N(0.1, 0.8), N(0.15, 0.8), N(0.2, 0.8)
my_models_scores = np.array([np.random.normal(loc=loc, scale=0.8, size=N) for loc in np.arange(0.1, 0.1 + 0.05 * M, step=0.05)])

eps_min = multi_aso(my_models_scores, confidence_level=0.95, seed=seed)

# eps_min =
# array([[1.       , 0.92621655, 1.        ],
#       [1.        , 1.        , 1.        ],
#       [0.82081635, 0.73048716, 1.        ]])

Model comparisons: 100%|█████████▉| 2992/3000 [00:21<00:00, 102.38it/s]

In [21]:
my_models_scores

array([[ 0.47714813, -0.85278056,  1.24616557, -0.15012152, -0.47647099],
       [ 0.85973035,  0.83767073, -0.3592188 ,  0.1625571 , -1.64414796],
       [ 1.12002858,  0.99355682,  0.9626593 , -1.41700386, -0.06726189]])

In [22]:
eps_min

array([[1.        , 0.92621655, 1.        ],
       [1.        , 1.        , 1.        ],
       [0.82081635, 0.73048716, 1.        ]])

In [3]:
import numpy as np
from deepsig import bootstrap_power_analysis

scores = np.random.normal(loc=0, scale=20, size=5)  # Create too small of a sample with high variance
power = bootstrap_power_analysis(scores, show_progress=False)  # 0.081, way too low

scores2 = np.random.normal(loc=0, scale=20, size=50)  # Let's collect more samples
power2 = bootstrap_power_analysis(scores2, show_progress=False)  # Better power with 0.2556

In [26]:
scores3 = np.random.normal(loc=0, scale=20, size=5)  # Let's collect more samples
power3 = bootstrap_power_analysis(scores2, show_progress=False)
print(power3)

0.2308


In [4]:
print(power)
print(power2)

0.1058
0.2484
